import type { Metadata } from 'next';
import { LegalShell } from '@/components/LegalShell';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'The terms and conditions for using fork ai.',
  alternates: { canonical: '/terms' },
};

const LAST_UPDATED = '7 June 2026';
const CONTACT = 'info@stemlabs.co.in';

export default function TermsPage() {
  return (
    <LegalShell title="Terms &amp; Conditions" updated={LAST_UPDATED}>
      <h2>1. Agreement</h2>
      <p>
        By accessing or using fork ai, you agree to be bound by these Terms and Conditions. If you
        disagree with any part, please do not use the service.
      </p>

      <h2>2. About fork ai</h2>
      <p>
        fork ai is an AI-powered branching research workspace operated by{' '}
        <strong>CURIOSTEM LEARNING PRIVATE LIMITED</strong> — RSF No 34/3, Door No 155/1, Sakthi Nagar,
        Thindal, Erode – 638012, Tamil Nadu, India. GST: 33AAMCC6984A1ZM.
      </p>

      <h2>3. Accounts &amp; Eligibility</h2>
      <ul>
        <li>You must be at least 13 years old to use fork ai.</li>
        <li>You are responsible for maintaining the security of your account credentials.</li>
        <li>One account per person. We reserve the right to terminate duplicate accounts.</li>
        <li>You agree to provide accurate information when creating your account.</li>
      </ul>

      <h2>4. Credits &amp; Billing</h2>
      <ul>
        <li>fork ai operates on a prepaid credit model. Credits are denominated in USD.</li>
        <li>
          New accounts receive a one-time complimentary signup credit. The amount is subject to change
          without notice.
        </li>
        <li>Credits are non-refundable once purchased, except as required by applicable law.</li>
        <li>
          Payments are processed by Razorpay in INR at the prevailing exchange rate at the time of
          purchase. Exchange rate fluctuations may affect the effective USD value of your credit.
        </li>
        <li>
          LLM calls consume credits based on token usage (input + output tokens), multiplied by a usage
          multiplier. The effective rate is visible in your account billing panel.
        </li>
        <li>Guest sessions (via share links) consume credits from the session owner&rsquo;s account.</li>
        <li>
          We reserve the right to adjust pricing and the credit multiplier. Changes take effect for new
          calls and will be communicated in advance where practicable.
        </li>
        <li>Unused credits do not expire, but we reserve the right to expire credits with at least 90 days&rsquo; notice.</li>
      </ul>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Reverse-engineer, scrape, or exploit the service beyond its intended purpose.</li>
        <li>Use fork ai to generate harmful, illegal, deceptive, or abusive content.</li>
        <li>Attempt to circumvent usage limits, billing, or authentication.</li>
        <li>Resell, sublicense, or redistribute access to the service.</li>
        <li>Use automated scripts to generate content at scale without prior written consent.</li>
      </ul>

      <h2>6. Guest Access &amp; Sharing</h2>
      <p>
        Share links grant read and LLM-branch access to a specific research session. Session owners are
        responsible for all LLM costs incurred by guests via their share link. Revoke share links at any
        time to remove guest access. We are not liable for content created by guests.
      </p>

      <h2>7. Content &amp; Intellectual Property</h2>
      <ul>
        <li>
          Research content generated by the LLM is provided for informational purposes only. We make no
          representations as to its accuracy, completeness, or fitness for any particular purpose.
        </li>
        <li>
          You retain ownership of your input queries. You grant CURIOSTEM LEARNING PRIVATE LIMITED a
          limited, non-exclusive licence to process them solely to provide the service.
        </li>
        <li>
          The fork ai platform, brand, design, and codebase are owned by CURIOSTEM LEARNING PRIVATE
          LIMITED. All rights reserved.
        </li>
      </ul>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, CURIOSTEM LEARNING PRIVATE LIMITED shall not be
        liable for any indirect, incidental, special, or consequential damages arising from your use of
        fork ai. Our total aggregate liability for any claim shall not exceed the credit balance held in
        your account at the time of the claim.
      </p>

      <h2>9. Privacy &amp; Data</h2>
      <p>
        Your research sessions are stored in AWS infrastructure (ap-south-1). Queries are processed
        through third-party AI model providers. We do not sell your personal data. By using fork ai you
        consent to this processing. See our <a href="/privacy-policy">Privacy Policy</a> for details.
      </p>

      <h2>10. Termination</h2>
      <p>
        We reserve the right to suspend or terminate accounts that violate these Terms, with or without
        notice. Unused credits at termination are non-refundable unless required by law.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive
        jurisdiction of the courts of Erode, Tamil Nadu, India.
      </p>

      <h2>12. Changes to These Terms</h2>
      <p>
        We may update these Terms at any time. Continued use of fork ai after changes are published
        constitutes your acceptance of the revised Terms. Material changes will be communicated via email
        where practicable.
      </p>

      <h2>13. Contact</h2>
      <p>
        For questions about these Terms, contact us at <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
    </LegalShell>
  );
}
