export const USER_META_MODEL = 'USER_META_MODEL';
export const SESSION_META_MODEL = 'SESSION_META_MODEL';
export const NODE_MODEL = 'NODE_MODEL';
export const ANNOTATION_MODEL = 'ANNOTATION_MODEL';
export const HIGHLIGHT_MODEL = 'HIGHLIGHT_MODEL';
export const SHARE_TOKEN_MODEL = 'SHARE_TOKEN_MODEL';
export const DYNAMO_TABLE = 'DYNAMO_TABLE';
